/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 lotus_elise.glb --transform 
Files: lotus_elise.glb [24.49MB] > /home/yahya/Desktop/Projects/my-awesome-project/porto/public/models/lotus_elise-transformed.glb [1.72MB] (93%)
Author: Stéphane Agullo (https://sketchfab.com/sa3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lotus-elise-75e9045ac1af4cdbb69318108c81edfd
Title: LOTUS ÉLISE
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Lotus_elise(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/lotus_elise-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.014}>
          <group name="LOTUS-def3Layer1" position={[0, 60.841, 0]}>
            <mesh name="LOTUS-def3Layer1_CARblack_0" geometry={nodes['LOTUS-def3Layer1_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer1_CARfeu_0" geometry={nodes['LOTUS-def3Layer1_CARfeu_0'].geometry} material={materials.PaletteMaterial002} />
            <mesh name="LOTUS-def3Layer1_CARcarros_0" geometry={nodes['LOTUS-def3Layer1_CARcarros_0'].geometry} material={materials.PaletteMaterial003} />
          </group>
          <group name="LOTUS-def3Layer2" position={[-75, 35.043, -121]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh name="LOTUS-def3Layer2_CARchrome_0" geometry={nodes['LOTUS-def3Layer2_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
            <mesh name="LOTUS-def3Layer2_CARblack_0" geometry={nodes['LOTUS-def3Layer2_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer2_CARlogo_0" geometry={nodes['LOTUS-def3Layer2_CARlogo_0'].geometry} material={materials['CAR.logo']} />
          </group>
          <group name="LOTUS-def3Layer16" position={[75, 35.096, -121]}>
            <mesh name="LOTUS-def3Layer16_CARchrome_0" geometry={nodes['LOTUS-def3Layer16_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
            <mesh name="LOTUS-def3Layer16_CARblack_0" geometry={nodes['LOTUS-def3Layer16_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer16_CARlogo_0" geometry={nodes['LOTUS-def3Layer16_CARlogo_0'].geometry} material={materials['CAR.logo']} />
          </group>
          <group name="LOTUS-def3Layer17" position={[-75, 35.08, 125]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh name="LOTUS-def3Layer17_CARchrome_0" geometry={nodes['LOTUS-def3Layer17_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
            <mesh name="LOTUS-def3Layer17_CARblack_0" geometry={nodes['LOTUS-def3Layer17_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer17_CARlogo_0" geometry={nodes['LOTUS-def3Layer17_CARlogo_0'].geometry} material={materials['CAR.logo']} />
          </group>
          <group name="LOTUS-def3Layer18" position={[75, 35.084, 125]}>
            <mesh name="LOTUS-def3Layer18_CARchrome_0" geometry={nodes['LOTUS-def3Layer18_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
            <mesh name="LOTUS-def3Layer18_CARblack_0" geometry={nodes['LOTUS-def3Layer18_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer18_CARlogo_0" geometry={nodes['LOTUS-def3Layer18_CARlogo_0'].geometry} material={materials['CAR.logo']} />
          </group>
          <group name="LOTUS-def3Layer6" position={[0, 60.841, 0]}>
            <mesh name="LOTUS-def3Layer6_CARblack_0" geometry={nodes['LOTUS-def3Layer6_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer6_CARchrome_0" geometry={nodes['LOTUS-def3Layer6_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
            <mesh name="LOTUS-def3Layer6_CARverre_0" geometry={nodes['LOTUS-def3Layer6_CARverre_0'].geometry} material={materials.PaletteMaterial005} />
            <mesh name="LOTUS-def3Layer6_CARfeu-2_0" geometry={nodes['LOTUS-def3Layer6_CARfeu-2_0'].geometry} material={materials.PaletteMaterial002} />
            <mesh name="LOTUS-def3Layer6_CARcarros_0" geometry={nodes['LOTUS-def3Layer6_CARcarros_0'].geometry} material={materials.PaletteMaterial003} />
            <mesh name="LOTUS-def3Layer6_CARecusson_0" geometry={nodes['LOTUS-def3Layer6_CARecusson_0'].geometry} material={materials['CAR.ecusson']} />
            <mesh name="LOTUS-def3Layer6_CARlamp-arr-bas_0" geometry={nodes['LOTUS-def3Layer6_CARlamp-arr-bas_0'].geometry} material={materials.PaletteMaterial006} />
            <mesh name="LOTUS-def3Layer6_CARlamp-avant-bas_0" geometry={nodes['LOTUS-def3Layer6_CARlamp-avant-bas_0'].geometry} material={materials.PaletteMaterial007} />
            <mesh name="LOTUS-def3Layer6_CARlamp-avant-haut_0" geometry={nodes['LOTUS-def3Layer6_CARlamp-avant-haut_0'].geometry} material={materials.PaletteMaterial008} />
            <mesh name="LOTUS-def3Layer6_CARlamp-avant-milieu_0" geometry={nodes['LOTUS-def3Layer6_CARlamp-avant-milieu_0'].geometry} material={materials.PaletteMaterial009} />
            <mesh name="LOTUS-def3Layer6_CARplaque_0" geometry={nodes['LOTUS-def3Layer6_CARplaque_0'].geometry} material={materials['CAR.plaque']} />
          </group>
          <group name="LOTUS-def3Layer7" position={[-86.301, 60.841, -66.915]}>
            <mesh name="LOTUS-def3Layer7_CARgris_0" geometry={nodes['LOTUS-def3Layer7_CARgris_0'].geometry} material={materials.PaletteMaterial002} />
            <mesh name="LOTUS-def3Layer7_CARblack_0" geometry={nodes['LOTUS-def3Layer7_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer7_CARcarros_0" geometry={nodes['LOTUS-def3Layer7_CARcarros_0'].geometry} material={materials.PaletteMaterial003} />
            <mesh name="LOTUS-def3Layer7_CARverre_0" geometry={nodes['LOTUS-def3Layer7_CARverre_0'].geometry} material={materials.PaletteMaterial005} />
            <mesh name="LOTUS-def3Layer7_CARchrome_0" geometry={nodes['LOTUS-def3Layer7_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
          </group>
          <group name="LOTUS-def3Layer8" position={[86.288, 60.841, -66.913]}>
            <mesh name="LOTUS-def3Layer8_CARgris_0" geometry={nodes['LOTUS-def3Layer8_CARgris_0'].geometry} material={materials.PaletteMaterial002} />
            <mesh name="LOTUS-def3Layer8_CARblack_0" geometry={nodes['LOTUS-def3Layer8_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer8_CARcarros_0" geometry={nodes['LOTUS-def3Layer8_CARcarros_0'].geometry} material={materials.PaletteMaterial003} />
            <mesh name="LOTUS-def3Layer8_CARverre_0" geometry={nodes['LOTUS-def3Layer8_CARverre_0'].geometry} material={materials.PaletteMaterial005} />
            <mesh name="LOTUS-def3Layer8_CARchrome_0" geometry={nodes['LOTUS-def3Layer8_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
          </group>
          <group name="LOTUS-def3Layer9" position={[0, 60.841, 0]}>
            <mesh name="LOTUS-def3Layer9_CARblack_0" geometry={nodes['LOTUS-def3Layer9_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer9_CARverre_0" geometry={nodes['LOTUS-def3Layer9_CARverre_0'].geometry} material={materials.PaletteMaterial005} />
            <mesh name="LOTUS-def3Layer9_CARmirroir_0" geometry={nodes['LOTUS-def3Layer9_CARmirroir_0'].geometry} material={materials.PaletteMaterial002} />
          </group>
          <group name="LOTUS-def3Layer10" position={[0, 60.841, 0]}>
            <mesh name="LOTUS-def3Layer10_CARchrome_0" geometry={nodes['LOTUS-def3Layer10_CARchrome_0'].geometry} material={materials.PaletteMaterial004} />
            <mesh name="LOTUS-def3Layer10_CARblack_0" geometry={nodes['LOTUS-def3Layer10_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="LOTUS-def3Layer11" position={[0, 60.841, 0]}>
            <mesh name="LOTUS-def3Layer11_CARblack_0" geometry={nodes['LOTUS-def3Layer11_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="LOTUS-def3Layer5" position={[0, 60.841, 0]}>
            <mesh name="LOTUS-def3Layer5_CARgris_0" geometry={nodes['LOTUS-def3Layer5_CARgris_0'].geometry} material={materials.PaletteMaterial002} />
            <mesh name="LOTUS-def3Layer5_CARblack_0" geometry={nodes['LOTUS-def3Layer5_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
            <mesh name="LOTUS-def3Layer5_CARverre_0" geometry={nodes['LOTUS-def3Layer5_CARverre_0'].geometry} material={materials.PaletteMaterial005} />
          </group>
          <group name="LOTUS-def3Layer12" position={[-30.191, 71.321, -43.763]} rotation={[-0.199, 0, 0]}>
            <mesh name="LOTUS-def3Layer12_CARgris_0" geometry={nodes['LOTUS-def3Layer12_CARgris_0'].geometry} material={materials.PaletteMaterial002} />
            <mesh name="LOTUS-def3Layer12_CARlogo_0" geometry={nodes['LOTUS-def3Layer12_CARlogo_0'].geometry} material={materials['CAR.logo']} />
            <mesh name="LOTUS-def3Layer12_CARblack_0" geometry={nodes['LOTUS-def3Layer12_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="Girl1" position={[-31.155, -42.943, 6.97]} rotation={[-Math.PI, 0, -Math.PI]} scale={0.9}>
            <group name="Object_72">
              <primitive object={nodes._rootJoint} />
              <skinnedMesh name="Object_75" geometry={nodes.Object_75.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_75.skeleton} />
              <skinnedMesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_76.skeleton} />
              <skinnedMesh name="Object_77" geometry={nodes.Object_77.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_77.skeleton} />
              <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_78.skeleton} />
              <skinnedMesh name="Object_79" geometry={nodes.Object_79.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_79.skeleton} />
              <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.PaletteMaterial002} skeleton={nodes.Object_80.skeleton} />
            </group>
          </group>
          <group name="LOTUS-def3Layer13" position={[0, 60.841, -21.477]}>
            <mesh name="LOTUS-def3Layer13_CARblack_0" geometry={nodes['LOTUS-def3Layer13_CARblack_0'].geometry} material={materials.PaletteMaterial001} />
          </group>
          <group name="LOTUS-def3Layer3" position={[0, 2, 0]} scale={[1.142, 1, 1]}>
            <mesh name="LOTUS-def3Layer3_SHADE_0" geometry={nodes['LOTUS-def3Layer3_SHADE_0'].geometry} material={materials.SHADE} />
          </group>
          <group name="Camera" position={[4168.26, 829, -6507.639]} rotation={[Math.PI, -1.011, 3.033]} />
        </group>
        <mesh name="SOL01_SOL_0" geometry={nodes.SOL01_SOL_0.geometry} material={materials.material} scale={0.014} />
      </group>
    </group>
  )
}

useGLTF.preload('/lotus_elise-transformed.glb')
