/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 yahya.glb --transform 
Files: yahya.glb [8.91MB] > /home/yahya/Desktop/Projects/my-awesome-project/porto/public/models/yahya-transformed.glb [1.21MB] (86%)
*/

import React from 'react'

import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Yahya(props) {
  const { nodes, materials } = useGLTF('/models/yahya-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bEngine_Geo_lodA_Engine_Geo_lodA_BMW_VarisM4GTSRewardRecyc.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016EngineA_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bGrille2_Geo_lodA_Grille2_Geo_lodA_BMW_VarisM4GTSRewardRec.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016Grille2A_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bGrille3_Geo_lodA_Grille3_Geo_lodA_BMW_VarisM4GTSRewardRec.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016Grille3A_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Badge_Geo_lodA_Kit4_Badge_Geo_lodA_BMW_VarisM4GTSRew.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016BadgeB_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Base_Geo_lodA_Kit4_Base_Geo_lodA_BMW_VarisM4GTSRewar.geometry} material={materials.PaletteMaterial001} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Carbon1_Geo_lodA_Kit4_Carbon1_Geo_lodA_BMW_VarisM4GT.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016_CallipersCalliperGlos_3a7479} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Carbon2_Geo_lodA_Kit4_Carbon2_Geo_lodA_BMW_VarisM4GT.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016Carbon2_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Coloured_Geo_lodA_Kit4_Coloured_Geo_lodA_BMW_VarisM4.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016Coloured_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Grille1_Geo_lodA_Kit4_Grille1_Geo_lodA_BMW_VarisM4GT.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016Grille1A_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Grille4_Geo_lodA_Kit4_Grille4_Geo_lodA_BMW_VarisM4GT.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016Grille4A_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Grille5_Geo_lodA_Kit4_Grille5_Geo_lodA_BMW_VarisM4GT.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016Grille5A_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Interior_Geo_lodA_Kit4_Interior_Geo_lodA_BMW_VarisM4.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016InteriorB_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Light_Geo_lodA_Kit4_Light_Geo_lodA_BMW_VarisM4GTSRew.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016LightB_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_ManufacturerPlate_Geo_lodA_Kit4_ManufacturerPlate_Ge.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016ManufacturerPlateC_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Paint_Geo_lodA_Kit4_Paint_Geo_lodA_BMW_VarisM4GTSRew.geometry} material={materials.PaletteMaterial002} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_SpecularTint_Geo_lodA_Kit4_SpecularTint_Geo_lodA_BMW.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016SpecularTintA_Material1} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bKit4_Window_Geo_lodA_Kit4_Window_Geo_lodA_BMW_VarisM4GTSR.geometry} material={materials.PaletteMaterial003} position={[0, 0.001, 0]} rotation={[-0.016, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.bpolySurface1_bBMW_VarisM4GTSRewardRecycled_2016_Wheel1A_3D_3.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016_Wheel1A_3D_3DWheel6B_Materia} position={[0.008, 0.003, 0.014]} rotation={[0, 0, 0.035]} scale={0.01} />
      <mesh geometry={nodes.bpolySurface603_bBMW_VarisM4GTSRewardRecycled_2016_CallipersC.geometry} material={materials.bBMW_VarisM4GTSRewardRecycled_2016_CallipersCalliperBadg_54b028} position={[0.008, 0.003, 0.014]} rotation={[0, 0, 0.035]} scale={0.01} />
      <mesh geometry={nodes.bpolySurface607_bphong2_0.geometry} material={materials.PaletteMaterial004} position={[0.008, 0.003, 0.014]} rotation={[0, 0, 0.035]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/yahya-transformed.glb')
